services:
  backend:
    build: ./Backend
    container_name: digi_prod
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build: ./Frontend
    container_name: react_app
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
